package com.agm.agrimitra.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/whatsapp")
@Slf4j
@Tag(name = "WhatsApp Webhook Controller", description = "Endpoints for Meta WhatsApp Cloud API webhook verification and event reception")
public class WhatsAppWebhookController {

    @Value("${whatsapp.verify-token:}")
    private String configuredVerifyToken;

    /**
     * Meta WhatsApp Cloud API verification handshake.
     * Meta sends a GET request to verify ownership of the webhook URL.
     *
     * @param mode        Must be "subscribe"
     * @param verifyToken Verification token matching the one configured in Meta App Dashboard
     * @param challenge   Arbitrary challenge string generated by Meta
     * @return Raw challenge string as text/plain with HTTP 200 if valid, or HTTP 403 Forbidden
     */
    @GetMapping(value = "/webhook", produces = MediaType.TEXT_PLAIN_VALUE)
    @Operation(summary = "Meta WhatsApp Cloud API verification handshake")
    public ResponseEntity<String> verifyWebhook(
            @RequestParam("hub.mode") String mode,
            @RequestParam("hub.verify_token") String verifyToken,
            @RequestParam("hub.challenge") String challenge) {

        log.info("Received WhatsApp webhook verification request: hub.mode={}, hub.verify_token={}", mode, verifyToken);

        if ("subscribe".equals(mode) && configuredVerifyToken != null && !configuredVerifyToken.isBlank()
                && configuredVerifyToken.equals(verifyToken)) {
            log.info("WhatsApp webhook verification successful. Returning hub.challenge");
            return ResponseEntity.ok()
                    .contentType(MediaType.TEXT_PLAIN)
                    .body(challenge);
        }

        log.warn("WhatsApp webhook verification failed. Mode: {}, token match: {}",
                mode, (configuredVerifyToken != null && configuredVerifyToken.equals(verifyToken)));
        return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
    }

    /**
     * Meta WhatsApp Cloud API event notification receiver.
     * Receives incoming messages, delivery statuses, and read receipts.
     * Fast HTTP 200 acknowledgment is required to avoid webhook delivery retries.
     *
     * @param rawBody Raw JSON payload sent by Meta
     * @return HTTP 200 OK with empty body
     */
    @PostMapping("/webhook")
    @Operation(summary = "Receive incoming WhatsApp Cloud API events and messages")
    public ResponseEntity<Void> receiveWebhook(@RequestBody(required = false) String rawBody) {
        log.info("WhatsApp webhook received: {}", rawBody);
        return ResponseEntity.ok().build();
    }
}
